name: Enable auto-merge for Dependabot PRs

# Opt into Node.js 24 for JavaScript actions to silence deprecation warnings
# See: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  enable-auto-merge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for this PR
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
